### ISSUE TITLE
waitUntil() throws InvalidSelectorError: Unable to locate an element with the xpath expression

### ISSUE THREAD

**Issue by thejavatar** [seleniumQuery/seleniumQuery#91] opened 2015-05-11 13:33 UTC
Hello,

I try to use seleniumQuery to navigate through a website with dynamically changed content (meaning it changes with page refresh). When I open the website in browser there is a button I need to click, but the button appears only after some time.

In Selenium IDE I use a waitForElementPresent command to wait for this button to appear before I fire it up. I tried the following code to copy this behaviour in seleniumQuery

```java
 $(".custom-dropdown-arrow-major").waitUntil().is(":present"); // tried also with :visible
```

But I receive following error:
>Caused by: org.openqa.selenium.InvalidSelectorException: The given selector (.//*[contains(concat(' ', normalize-space(@class), ' '), ' custom-dropdown-arrow-major ')]) is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: Unable to locate an element with the xpath expression (.//*[contains(concat(' ', normalize-space(@class), ' '), ' custom-dropdown-arrow-major ')]) because of the following error:
TypeError: Argument 1 of Document.createNSResolver is not an object.

Whereas in webdriver this work:
```java
WebDriverWait wait = new WebDriverWait(driver.get(), 100);
wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("custom-dropdown-arrow-major")));
```

[Edit]

I assume problem starts with $ contructor, where right at the begininng elements are retrieved.

```java
	protected SeleniumQueryObject(WebDriver driver, String selector) {
		this.driver = driver;
		this.by = SeleniumQueryBy.byEnhancedSelector(selector);
		this.elements = toImmutableRandomAccessList(driver.findElements(this.by));
		this.previous = null;
	}
```

Would it make sense to make this attribute lazy initialized? In that case the exception would not be fired upon `$().waitUntil()` but at the same time it shouldn't affect the rest of code. I would be happy to make the change if you agree on solution.

**Comment by acdcjunior** [comment] 2015-05-11 21:53
Humm... Interesting! I've never seen that problem. What Selenium is in your classpath? 2.45? (If you use no other tool than seleniumQuery, then it is 2.44, actually.)

This seems like a bug in the XPath module of Selenium itself. Check [this thread](https://code.google.com/p/selenium/issues/detail?id=8600). If the poster is right, the problem is specific to 2.45.
The [#8](https://code.google.com/p/selenium/issues/detail?id=8600#c8) comment says it should be fixed, but, telling from the date, the patch didn't make it into a release yet.

About the lazy loading, the `$().waitUntil()` actually requeries the DOM several times before failing into a timeout exception. I mean, even if it found no elements at the constructor, it would for sure try again. Well, at least that's what we designed it to do.

How frequent is it for you? Can you reproduce it consistently?
We could try to work something out, though if the problem is specific to 2.45, falling back to 2.44 till 2.46 comes may be a solution right now.

As for the changes, feel free to improve anything you think deserves improvement! Right now I'm working on yet another selector system (I wanted to implement `:hidden` and similar selectors, they are tricky because you can't map them to XPath, you have to iterate through the result calling `.isVisible`) so I apologize for some of the messy code that is around. But this should change in the future!

Cheers!!

**Comment by thejavatar** [comment] 2015-05-11 22:24
I have 2.45 on the classpath. I will give it a try with 2.44 when I'm at work tomorrow morning. 

It's crazy consistent, 10 out of 10 times I get this error. Nevertheless, for now as a workaround I'm using standard webdriver waiting API (see snippet from the first post) and it works fine. I just hate mixing seleniumQuery with pure webdriver. I didn't see anything in the code (maybe I was not paying enough attention) that would reexecute the search when failed on the first attempt. Is this done by some kind of aspect or did I miss it big time?

In general good job on the tool! I found it when I was looking for solution that could allow me to find elements by their content, which seems to be unsupported in the webdriver itself.

I will let you know tomorrow about 2.44!

Cheers.

**Comment by acdcjunior** [comment] 2015-05-11 22:58
The waiting functions are pretty much Selenium's Fluent wait system only. seleniumQuery doesn't add much voodoo, all it attempts to be is syntatic sugar. That's probably too much detail, but here's what it does:

When you [call `$().waitUntil()`](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/SeleniumQueryObject.java#L148), it [instantiates a `SeleniumQueryWaitUntil` basically saying "this is the sqObject you will wait for; use the default timeout and polling times"](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryWaitUntil.java#L47).

The real waiting happens when we follow up with the [call to `.is()`](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryWaitUntil.java#L76), because it calls the [`SeleniumQueryFluentWait#waitUntil`](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryFluentWait.java#L35) method that will end up [asking for the creation](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryFluentWait.java#L39) of a [vanilla Selenium `FluentWait` object](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryFluentWait.java#L48) which will be the responsible for the waiting (notice we just send the `By` as argument, the `FluentWait` will use it to requery).

After Selenium is done waiting (assuming it didn't timeout), we [pick the elements returned](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryFluentWait.java#L39) and [rebuild the `SeleniumQueryObject`](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/wait/SeleniumQueryFluentWait.java#L40), returning it.

We use it everyday in our company, with literally thousands of tests using it. There are a lot of improvements to go, still. But this rework of the selector system is really taking a lot...

**Comment by thejavatar** [comment] 2015-05-11 23:12
That's more or less what I understood, nevertheless thanks for clarification! It's just a pitty cause right now it fails for me before actually calling `waitUntil()` method.

When `$()` is invoked it executes `driver.findElements(this.by)` in constructor of SeleniumQueryObject. This method is executed from webdriver itself with no waiting capabilities so my guess was: no wonder it fails as the element appears in browser in around 15 seconds. And I bet the `findElements()` method from webdriver will time out before that time. So maybe after the implementation on seleniumQuery side is not perfect as well?

Also it's a pitty cause then when `waitUntill()` method is invoked it actually does not utilize the result of `driver.findElements(this.by)`as it rebuilds SeleniumQueryObject with new elements, rewriting only QueryBy and Webdriver from initial SeleniumQueryObject.

**Comment by thejavatar** [comment] 2015-05-12 09:07
I'm running into this error: https://code.google.com/p/selenium/issues/detail?id=6215 with 2.44, 2.43, 2.42. It seems that for Firefox 37.0.2, a working version of the Selenium is the latest 2.45

I tried to get into Selenium API code but this one makes magic for sure. Let's imagine that we execute in `driver.findElements()` webdrive, it retries to retrieve the object for 30s, but the element shows up on the page after 60s, and that's the value I have set up to wait in seleniumQuery in `waitUntil()`. This will always break, casue even when usinig `waintUnitl()`, seleniumQuery tries to retrieve first the element using regular webdrive method (`findElements()`), that will error out after 30s.

**Comment by acdcjunior** [comment] 2015-05-22 17:32
Hmm... very interesting point!
I made the constructor fetch the elements in an attempt to make the `SeleniumQueryObject` immutable (and then make everything else, such as thread-safety, easier). Also this is the way the `$()` constructor of jQuery handles things.

But, thinking better about it now you say that, at first glance nothing stops us from having those matched elements being lazily fetched. This would not trigger the first `findElements()` when the function called is `.waitUntil()` and others, effectively solving your issue.

If I got it right, that's very doable. But, tell me, is that what you meant, did I get it right?

**Comment by thejavatar** [comment] 2015-07-19 08:50
Hi, sorry, somehow I missed your update. Yes, that was exactly what I was thinking about.

**Comment by acdcjunior** [comment] 2016-03-24 16:41
Hey, there. I'm closing old issues and this was (or at least it seemed to be) a `selenium-java` problem.
It is now at version `2.53.0` and hopefully we won't be getting that error anymore.
Cheers.

**Closed by acdcjunior** 2016-03-24 16:41 UTC
Labels: external bug

**Comment by athenatk** [comment] 2016-04-08 18:00
Hello All, 

I am getting this error with Selenium 2.53.0 running with Ruby 2.2.4 against chromedriver=2.15.322455 and chrome=49.0.2623.110.
How to resolve?  Thank you!
``
/Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': invalid selector: Unable to locate an element with the xpath expression //*[@id='instructions_for_users']/header/hgroup/h2 because of the following error: (Selenium::WebDriver::Error::InvalidSelectorError)
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
  (Session info: chrome=49.0.2623.110)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:596:in `find_element_by'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/search_context.rb:61:in `find_element'
	from /Users/cbay/Automation/selenium/createTestFunctions.rb:168:in `block in website_test'
	from /Users/cbay/.rvm/gems/ruby-2.2.4/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/wait.rb:58:in `until'
	from /Users/cbay/Automation/selenium/createTestFunctions.rb:168:in `website_test'
	from createTest.rb:73:in `block in <main>'
	from createTest.rb:63:in `each'
	from createTest.rb:63:in `<main>'`>
``

**Comment by acdcjunior** [comment] 2016-04-08 18:20
@athenatk Your problem is related to [Selenium](https://github.com/SeleniumHQ/selenium) directly, not seleniumQuery (which is in Java). You should open an issue for that at https://github.com/SeleniumHQ/selenium .
